<?php
// STATUS: DIAMANT VGT SUPREME
declare(strict_types=1);

namespace Astraea\VLP\Light\Admin;

use Astraea\Auth\StepUpAuthService;
use Astraea\Exceptions\SecurityException;
use Astraea\Exceptions\ValidationException;
use Astraea\Security\SecurityEventManager;
use Astraea\VLP\Light\Consent\ServiceRegistry;
use Astraea\VLP\Light\Dattrack\DattrackService;
use Astraea\VLP\Light\Scanner\ScannerService;
use Astraea\VLP\Light\Settings;

final class AdminPage {
    public static function init(): void {
        add_action('admin_menu',[self::class,'menu']); add_action('admin_enqueue_scripts',[self::class,'assets']);
        add_action('admin_post_astraea_vlp_save_settings',[self::class,'saveSettings']);
        add_action('admin_post_astraea_vlp_save_service',[self::class,'saveService']);
        add_action('admin_post_astraea_vlp_delete_service',[self::class,'deleteService']);
        add_action('admin_post_astraea_vlp_scan',[self::class,'scan']);
    }
    public static function menu(): void { add_menu_page('VLP Light','VLP Light','manage_options','astraea-vlp-light',[self::class,'render'],'dashicons-privacy',59); }
    public static function assets(string $hook): void { if($hook!=='toplevel_page_astraea-vlp-light')return; $base=site_url('/astraea-core/VLP/Light/assets/'); wp_enqueue_style('astraea-vlp-admin',$base.'css/vlp-admin.css',['astraea-components'],Settings::VERSION); }
    public static function render(): void {
        if(!current_user_can('manage_options'))wp_die(esc_html__('Insufficient permissions.','astraeaos'));
        $tab=isset($_GET['tab'])?sanitize_key((string)wp_unslash($_GET['tab'])):'overview'; if(!in_array($tab,['overview','services','scanner','dattrack','settings'],true))$tab='overview';
        $scan=get_transient('astraea_vlp_scan_'.get_current_user_id()); $metrics=['events_7d'=>0,'visitor_days_7d'=>0,'last_event'=>'']; try{$metrics=DattrackService::metrics();}catch(\Throwable){}
        ?><div class="wrap avlp-admin"><div class="avlp-admin-hero"><div><span class="avlp-kicker">VISIONLEGALPRO · LIGHT EDITION</span><h1>Privacy Control Plane</h1><p>Consent, DOM Gatekeeper, Scanner und souveräne Dattrack-Analyse — direkt im AstraeaOS-Kernel.</p></div><div class="avlp-status"><b><?php echo Settings::isEnabled()?'ACTIVE':'DISABLED'; ?></b><span>Policy v<?php echo esc_html((string)Settings::policyVersion()); ?></span></div></div>
        <nav class="nav-tab-wrapper avlp-tabs"><?php foreach(['overview'=>'Übersicht','services'=>'Dienste','scanner'=>'Scanner','dattrack'=>'Dattrack','settings'=>'Einstellungen'] as $id=>$label): ?><a class="nav-tab <?php echo $tab===$id?'nav-tab-active':''; ?>" href="<?php echo esc_url(admin_url('admin.php?page=astraea-vlp-light&tab='.$id)); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></nav>
        <?php if($tab==='overview') self::overview($metrics); elseif($tab==='services') self::services(); elseif($tab==='scanner') self::scanner(is_array($scan)?$scan:null); elseif($tab==='dattrack') self::dattrack($metrics); else self::settings(); ?></div><?php
    }
    private static function overview(array $m): void { ?><div class="avlp-grid"><section class="avlp-panel"><span class="avlp-label">DOM GATEKEEPER</span><strong><?php echo Settings::isEnabled()?'ENFORCING':'DISABLED'; ?></strong><p>Optionale Drittanbieter-Ressourcen bleiben inert, bis die passende Kategorie freigegeben wurde.</p></section><section class="avlp-panel"><span class="avlp-label">DATTRACK</span><strong><?php echo Settings::dattrackEnabled()?'CONSENT-GATED':'DISABLED'; ?></strong><p><?php echo esc_html((string)$m['events_7d']); ?> Events · <?php echo esc_html((string)$m['visitor_days_7d']); ?> Visitor-Days / 7 Tage</p></section><section class="avlp-panel"><span class="avlp-label">SERVICES</span><strong><?php echo esc_html((string)count(ServiceRegistry::all())); ?></strong><p>Integrierte und eigene Klassifizierungsregeln.</p></section><section class="avlp-panel"><span class="avlp-label">CACHE SAFETY</span><strong><?php echo Settings::strictCache()?'STRICT':'CACHE-NEUTRAL'; ?></strong><p>Verhindert das Vermischen consentabhängiger HTML-Zustände in Shared Caches.</p></section></div><?php }
    private static function services(): void { $services=ServiceRegistry::all(); ?><div class="avlp-stack"><section class="avlp-panel"><h2>Dienst hinzufügen / bearbeiten</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="avlp-form"><input type="hidden" name="action" value="astraea_vlp_save_service"><?php wp_nonce_field('astraea_vlp_service'); ?><div class="avlp-form-grid"><label>ID<input name="id" required pattern="[a-z0-9_-]+"></label><label>Name<input name="name" required></label><label>Anbieter<input name="provider" required></label><label>Kategorie<select name="category"><?php foreach(Settings::CATEGORIES as $cat): ?><option value="<?php echo esc_attr($cat); ?>"><?php echo esc_html($cat); ?></option><?php endforeach; ?></select></label><label class="wide">Zweck<textarea name="purpose"></textarea></label><label>Hosts<textarea name="hosts" placeholder="example.com"></textarea></label><label>Code-Marker<textarea name="markers"></textarea></label><label>Cookie-Namen / Präfixe<textarea name="cookies"></textarea></label><label class="check"><input type="checkbox" name="active" value="1" checked> Aktiv</label><label>Passwort-Bestätigung (optional)<input type="password" name="astraea_stepup_password" placeholder="Nur nötig wenn Sitzung nicht autorisiert"></label></div><button class="button button-primary">Dienst speichern</button></form></section><section class="avlp-panel"><h2>Service Registry</h2><div class="avlp-service-list"><?php foreach($services as $s): ?><article><div><strong><?php echo esc_html((string)$s['name']); ?></strong><span><?php echo esc_html((string)$s['provider']); ?> · <?php echo esc_html((string)$s['category']); ?></span><small><?php echo esc_html((string)$s['purpose']); ?></small></div><div><span class="avlp-chip <?php echo !empty($s['active'])?'ok':'off'; ?>"><?php echo !empty($s['active'])?'ACTIVE':'OFF'; ?></span><?php if(empty($s['internal'])): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('astraea_vlp_delete_service'); ?><input type="hidden" name="action" value="astraea_vlp_delete_service"><input type="hidden" name="id" value="<?php echo esc_attr((string)$s['id']); ?>"><button class="button">Löschen</button></form><?php endif; ?></div></article><?php endforeach; ?></div></section></div><?php }
    private static function scanner(?array $scan): void { ?><section class="avlp-panel"><div class="avlp-panel-head"><div><h2>Privacy Scanner</h2><p>Analysiert gerenderte Startseite, Cookies, aktive Plugins und das aktive Theme innerhalb fester Pfad- und Größenlimits.</p></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('astraea_vlp_scan'); ?><input type="hidden" name="action" value="astraea_vlp_scan"><button class="button button-primary">Scan starten</button></form></div><?php if($scan): ?><p><b><?php echo esc_html((string)($scan['scanned_files']??0)); ?></b> Dateien · Scan <?php echo esc_html((string)($scan['scanned_at']??'')); ?></p><div class="avlp-findings"><?php foreach(($scan['findings']??[]) as $f): ?><article><span><?php echo esc_html((string)$f['type']); ?></span><strong><?php echo esc_html((string)($f['service_name']?:$f['evidence'])); ?></strong><small><?php echo esc_html((string)$f['source']); ?></small><code><?php echo esc_html((string)$f['evidence']); ?></code></article><?php endforeach; ?></div><?php else: ?><div class="avlp-empty">Noch kein Scan in dieser Sitzung.</div><?php endif; ?></section><?php }
    private static function dattrack(array $m): void { ?><div class="avlp-grid"><section class="avlp-panel"><span class="avlp-label">EVENTS · 7 TAGE</span><strong><?php echo esc_html((string)$m['events_7d']); ?></strong></section><section class="avlp-panel"><span class="avlp-label">VISITOR-DAYS · 7 TAGE</span><strong><?php echo esc_html((string)$m['visitor_days_7d']); ?></strong></section><section class="avlp-panel"><span class="avlp-label">LETZTES EVENT</span><strong class="small"><?php echo esc_html($m['last_event']?:'—'); ?></strong></section></div><section class="avlp-panel"><h2>Sovereign Analytics</h2><p>Dattrack Light sendet keine Daten an Dritte. Ereignisse werden nur nach Statistik-Einwilligung angenommen, mit täglich rotierendem HMAC-Identifier pseudonymisiert und über Astraea Crypto AEAD verschlüsselt gespeichert. Roh-IP-Adressen werden nicht gespeichert.</p></section><?php }
    private static function settings(): void {
        $userId = get_current_user_id();
        $isElevated = StepUpAuthService::isStepUpActive($userId);
        $verifyUrl = StepUpAuthService::getVerificationUrl(admin_url('admin.php?page=astraea-vlp-light&tab=settings'));
        ?><section class="avlp-panel"><h2>VLP Light Policy</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="avlp-form"><?php wp_nonce_field('astraea_vlp_settings'); ?><input type="hidden" name="action" value="astraea_vlp_save_settings"><label class="check"><input type="checkbox" name="enabled" value="1" <?php checked(Settings::isEnabled()); ?>> VLP Light aktiv</label><label class="check"><input type="checkbox" name="dattrack" value="1" <?php checked(Settings::dattrackEnabled()); ?>> Dattrack Light aktiv</label><label class="check"><input type="checkbox" name="strict_cache" value="1" <?php checked(Settings::strictCache()); ?>> Strict Cache Safety</label><label>Banner-Titel<input name="title" value="<?php echo esc_attr(Settings::title()); ?>"></label><label>Banner-Text<textarea name="text"><?php echo esc_textarea(Settings::text()); ?></textarea></label><label>Datenschutzerklärung-URL<input name="privacy_url" type="url" placeholder="https://..." value="<?php echo esc_attr((string)get_option(Settings::OPTION_PRIVACY_URL, '')); ?>"><small style="display:block;margin-top:4px;color:#94a3b8;">Freilassen f&uuml;r Standard-WordPress-Datenschutzseite (<?php echo esc_html(function_exists('get_privacy_policy_url') && get_privacy_policy_url() ? (string)get_privacy_policy_url() : 'Nicht festgelegt'); ?>)</small></label><div class="avlp-stepup-box"><?php if ($isElevated): ?><div class="avlp-stepup-status"><span class="avlp-chip ok">&#x2714; SITZUNG AUTORISIERT</span><small>Deine Sitzung ist f&uuml;r privilegierte &Auml;nderungen autorisiert.</small></div><?php else: ?><label>Administrator-Passwort (Sitzungs-Best&auml;tigung)<input type="password" name="astraea_stepup_password" autocomplete="current-password" placeholder="Passwort zur sofortigen Autorisierung"></label><p class="description">Die Datenschutz-Policy ist ein privilegiertes Sicherheitsmerkmal. Best&auml;tige hier direkt dein Passwort oder autorisiere deine Sitzung unter <a href="<?php echo esc_url($verifyUrl); ?>">Security &rarr; Sessions</a> f&uuml;r 15 Minuten.</p><?php endif; ?></div><button class="button button-primary">Policy speichern</button></form></section><?php
    }
    public static function saveSettings(): never { self::guard('astraea_vlp_settings','vlp:policy_change'); update_option(Settings::OPTION_ENABLED,!empty($_POST['enabled']),false); update_option(Settings::OPTION_DATTRACK,!empty($_POST['dattrack']),false); update_option(Settings::OPTION_STRICT_CACHE,!empty($_POST['strict_cache']),false); update_option(Settings::OPTION_BANNER_TITLE,mb_substr(sanitize_text_field((string)wp_unslash($_POST['title']??'')),0,160),false); update_option(Settings::OPTION_BANNER_TEXT,mb_substr(sanitize_textarea_field((string)wp_unslash($_POST['text']??'')),0,800),false); update_option(Settings::OPTION_PRIVACY_URL,esc_url_raw((string)wp_unslash($_POST['privacy_url']??'')),false); Settings::bumpPolicyVersion(); SecurityEventManager::recordEvent(SecurityEventManager::SEVERITY_INFO,'VLP','policy_changed','VLP Light policy was changed by an administrator.',['user_id'=>get_current_user_id()]); self::redirect('settings','saved'); }
    public static function saveService(): never { self::guard('astraea_vlp_service','vlp:service_change'); try{$s=ServiceRegistry::normalize($_POST);ServiceRegistry::save($s);SecurityEventManager::recordEvent(SecurityEventManager::SEVERITY_INFO,'VLP','service_saved','VLP service registry entry changed.',['service'=>(string)$s['id'],'user_id'=>get_current_user_id()]);self::redirect('services','saved');}catch(ValidationException){self::redirect('services','invalid');} }
    public static function deleteService(): never { self::guard('astraea_vlp_delete_service','vlp:service_delete'); try{ServiceRegistry::delete((string)wp_unslash($_POST['id']??''));self::redirect('services','deleted');}catch(ValidationException){self::redirect('services','invalid');} }
    public static function scan(): never { if(!current_user_can('manage_options'))wp_die('Forbidden','',['response'=>403]);check_admin_referer('astraea_vlp_scan');$result=ScannerService::scan();set_transient('astraea_vlp_scan_'.get_current_user_id(),$result,15*MINUTE_IN_SECONDS);SecurityEventManager::recordEvent(SecurityEventManager::SEVERITY_INFO,'VLP','scanner_completed','VLP Light privacy scan completed.',['findings'=>count($result['findings']??[]),'files'=>(int)($result['scanned_files']??0)]);self::redirect('scanner','scanned'); }
    private static function guard(string $nonce,string $action): void {
        if(!current_user_can('manage_options'))wp_die('Forbidden','',['response'=>403]);
        check_admin_referer($nonce);
        $userId = get_current_user_id();
        if (!empty($_POST['astraea_stepup_password']) && is_string($_POST['astraea_stepup_password'])) {
            try {
                if (StepUpAuthService::verifyStepUpChallenge($userId, (string)wp_unslash($_POST['astraea_stepup_password']))) {
                    return;
                }
            } catch (\Throwable) {}
        }
        try{
            StepUpAuthService::guardSensitiveAction($userId,$action);
        }catch(SecurityException){
            $verifyUrl = StepUpAuthService::getVerificationUrl(admin_url('admin.php?page=astraea-vlp-light&tab=settings'));
            $title = esc_html__('Step-Up Re-Authentication Required', 'astraeaos');
            $buttonText = esc_html__('Re-authenticate in Security → Sessions now', 'astraeaos');
            $msg = sprintf(
                esc_html__('Current-session re-authentication is required in Security → Sessions. %s', 'astraeaos'),
                '<br><br><a href="' . esc_url($verifyUrl) . '" class="button button-primary" style="display:inline-block;padding:8px 16px;text-decoration:none;border-radius:6px;">' . $buttonText . '</a>'
            );
            wp_die($msg, $title, ['response'=>403, 'back_link'=>true]);
        }
    }
    private static function redirect(string $tab,string $status): never { wp_safe_redirect(add_query_arg(['page'=>'astraea-vlp-light','tab'=>$tab,'vlp_status'=>$status],admin_url('admin.php')));exit; }
}
